#' @title lolligen: An Interactive Principal Component Analysis Visualization Tool
#'
#' @description
#' This function takes a principal component analysis (PCA) object via the
#' internal function pca_variances and generates several interactive visual aids
#' commonly required to analyze interindividual and multivariate variance in PCA.
#' This function primarily uses the **plotly** package to generate interactive
#' PCA plots between principal components as well as interactive lollipop graphs
#' showing the extreme shape variances for each meaningful principal component.
#'
#' @param Data_PCA a list object resembling or formed by the *pca_variances* function output.
#'
#' @param k an integer indicating the number of dimensions in the landmark configuration
#' prior to data transformation via PCA. Default value is 3.
#'
#' @param PCA_var an object from the *pca_variances* function output.
#'
#' @param ID a vector containing the identification names and/or numbers for each
#' observation from the principal component analysis.
#'
#' @param coord_name a vector listing the names of the landmark coordinates.
#'
#' @param Group a list object containing one or more grouping variable vectors.
#'
#' @param no.shape a boolean value indicating whether the function should
#' estimate and save the shape extremes of each important principal component.
#' Default value is set to FALSE. If set to TRUE, the function will not generate
#' interactive plots to visualize landmark variance based on each principal component.
#'
#' @param subset an optional vector listing a grouping variable for each landmark.
#' If subset is added and no.shape is set to FALSE, the landmark lollipop graph
#' will segment each of the landmarks by the subset grouping, allowing the user
#' to show and hide groups of landmarks to visualize specific shape variances.
#'
#' @details
#' This function requires a list object generated by the *gm.prcomp* function in
#' the *geomorph* package, or a list containing the same variables (i.e., principal
#' component scores, eigenvalues and eigenvectors, number of interested principal components,
#' number of dimensions). The function then uses the argument *PCA_var*, an output
#' from the *pca_variances* function, and generates automatically labeled,
#' interactive principal component plots that can be used to analyze
#' interindividual variation and also evaluate variable relationships through lollipop
#' graphs of the variables used to conduct the PCA. This function will accept
#' any list object for Data_PCA as long as it contains the following objects:
#' \itemize{
#'    \item *x*:   a data table of the principal component scores (columns) and observations (rows)
#'    \item *sdev*:  a data table containing the eigenvalues from the PCA.
#'    \item *rotation*:  a data table containing the rotation matrix or eigenvectors
#'    calculated during the PCA.
#'    \item *center*:  a 2D or 3D p x k x n array containing the mean variable configuration
#' }
#' Additionally, lolligen allows a list object containing vectors of group labels
#' for each observation in the landmark configuration. This function does not
#' conduct a between group PCA. If this is desired, Data_PCA should contain the values
#' output by a between groups PCA such as the *bgPCA* function from the **ade4** package.
#' From the data presented in Data_PCA, the function will generate convex hulls and color
#' the individuals by each grouping variable in the list and store each plot separately.
#'
#' @returns a list object containing the following:
#'
#' \itemize{
#'    \item *PCA_list*:  a list object containing all possible principal component plot pairs.
#'    \item *PC_mean_max_min*:   a list object containing the mean, maximum extreme,
#'    and minimum extreme shapes or combination of variables respectively for each
#'    meaningful principal component.
#'    \item *lollipop_PCs*:  a list containing a series of lollipop graph plots
#'    for each PC. Each plot already contains the mean, maximum, and minimum shape
#'    extremes to visualize the shape variations across each principal component.
#'    Keep in mind that double brackets are required to call each PC (see examples).
#'    \item *PCA_Group*:   an optional list object containing the names of each grouping
#'    variable supplied through the Group argument. If NULL, this object will
#'    not be generated. If argument Group is not NULL, a convex hull plot will be
#'    generated for each principal component pairing for each group vector in the list.
#' }
#'
#' @author
#' Brian Anthony Keeling
#'
#' @seealso \code{plotly} \code{hullgen}
#'
#' @importFrom plotly plot_ly add_trace layout
#' @importFrom grDevices png dev.off
#' @importFrom RColorBrewer brewer.pal
#' @importFrom dplyr filter
#' @importFrom ggplot2 ggplot aes geom_boxplot stat_summary theme element_text
#' @importFrom ggpubr theme_pubclean ggarrange annotate_figure text_grob
#'
#' @export
#'
#' @examples
#'
#' \dontrun{
#'
#' # Example 1: Without groupings or subsets
#'
#' # Import the sample 3D p x k x n array *Corpus_Land*
#' data(Corpus_Land)
#'
#' # Conduct a Principal Component Analysis on the 3D array using *gm.prcomp* from **geomorph**
#' Data_PCA = gm.prcomp(Corpus_Land)
#'
#' # Summarize the results with the pca_variances function
#' PCA_var = pca_variances(Data_PCA) # input object from the PCA
#'
#' # View the scree plot
#' PCA_var$Scree
#'
#' # View the number of meaningful PCs
#' PCA_var$PCs
#'
#' # Conduct the lolligen function and input the number of desired principal components.
#'
#' output <- lolligen(Data_PCA, # PCA object
#'                    k = 3, # three dimensional landmark data
#'                    PCA_var # output from the internal pca_variances function
#'                    )
#'
#' # Visualize individual variation between principal components 1 and 2
#' output$PCA_list$PC_1_2
#'
#' # Visualize
#'
#' # Visualize shape changes along PC 1
#'
#' output$lollipop_PCs[[1]]
#'
#' # Visualize shape changes along PC 2
#'
#' output$lollipop_PCs[[2]]
#'
#' # Save the plot
#'
#' saveWidget(output$lollipop_PCs[[1]], "PC_1_Shape_Changes.html")
#'
#' # Example 2: lolligen with groupings and subsetted landmarks
#'
#' # Import the sample dataset Corpus_Land
#' data(Corpus_Land)
#'
#' # Import the associated sample Biomechanical data for IDs and grouping variables.
#' data(Biomechanics)[1:119,1:3] # we are only interested in the groupings.
#'
#' # Conduct a Principal Component Analysis on the 3D array.
#' Data_PCA = gm.prcomp(Corpus_Land)
#'
#' # Summarize the results with the pca_variances function
#' PCA_var = pca_variances(Data_PCA) # input object from the PCA
#'
#' # Create a list containing randomized Grouping variables
#'
#' Group = list(Collection = Biomechanics$Collection)
#' ID = unique(Biomechanics$ID)
#'
#' # Conduct the lolligen function and input the number of desired principal components.
#'
#' output <- lolligen(Data_PCA, # PCA object
#'                    k = 3, # three dimensional landmark data
#'                    PCA_var, # output from the internal pca_variances function
#'                    ID = ID, # specimen IDs
#'                    coord_name = dimnames(Corpus_Land)[[[1]]], # landmark names
#'                    Group = Group, # list of grouping variables
#'                    no.shape = FALSE, # no mesh generation is required
#'                    subset = c(rep("LM1M2", "LP3P4", "Symphysis", "RP3P4", "RM1M2"), each = 120)
#'                    )
#'
#' # Visualize individual variation between principal components 1 and 2
#' output$PCA_list$PC_1_2
#'
#' # Visualize grouped PCA plot between principal components 1 and 2
#'
#' output$PCA_Group$Collection$PC_1_2
#'
#' # Visualize shape changes along PC 1
#'
#' output$lollipop_PCs[[1]]
#'
#' # Visualize shape changes along PC 2
#'
#' output$lollipop_PCs[[2]]
#'
#' }

lolligen <- function(Data_PCA,
                     PCs = 2,
                     k = 3,
                     PCA_var = NULL,
                     ID = NULL,
                     coord_name = NULL,
                     Group = NULL,
                     no.shape = FALSE,
                     subset = NULL) {

  lollipops = list()

  if(is.null(PCA_var)) {
    PCA_var = PCA_variances(Data_PCA)
    PCs <- as.numeric(PCA_var$PCs)
    PCA_var <- data.frame(PCA_var$PCA_var)
  }

  if (is.null(ID)) {
    ID <- c(rep(1:nrow(Data_PCA$x)))
  }

  if (is.null(coord_name)) {
    n_point = length(Data_PCA$center) / k
    coord_name = as.character(rep(1:n_point))
  }
  if(!is.null(Group)) {
    if(!"list" %in% class(Group)) {
      placeholder = list()
      if(!is.null(ncol(Group))){
        if(ncol(Group) > 1) {
          for(g in 1:ncol(Group)) {
            placeholder[[g]] <- Group[,g]
            placeholder[[g]] <- placeholder[[g]][[1]]
            names(placeholder)[g] <- colnames(Group[,g])
          }
          Group <- placeholder
        }
      } else {
        placeholder = list()
        placeholder[[1]] <- Group
        names(placeholder) <- "Group"
        Group = placeholder
      }
    }
  }

  generate_pc_sets <- function(n_pcs) { # helper function to automate pc plots
    pc_sets <- list()

    pc_sets$PC_1_2 <- list(pcs = c(1,2), min_dim = 2)

    if (n_pcs >= 3) {
      pc_sets$PC_1_2_3 <- list(pcs = c(1,2,3), min_dim = 3)
    }

    if (n_pcs >= 4) {
      pc_sets$PC_2_3_4 <- list(pcs = c(2,3,4), min_dim = 4)
      pc_sets$PC_3_4 <- list(pcs = c(3,4), min_dim = 4)
    }

    if(n_pcs >= 5) {
      for(i in seq(5, n_pcs, by = 1)) {
        if(i <= n_pcs) {
          # 3D plot for each group of 3
          pc_sets[[paste0("PC_", i-2, "_", i-1, "_", i)]] <-
            list(pcs = c(i-2, i-1, i), min_dim = i)

          # 2D plot for final two PCs in group
          pc_sets[[paste0("PC_", i-1, "_", i)]] <-
            list(pcs = c(i-1, i), min_dim = i)
        }
      }
    }
    return(pc_sets)
  }

  pc_sets <- generate_pc_sets(n_pcs = PCs) # Run the helper function and establish the sets

  create_plot_labels <- function(pcs, PCA_var) { # helper function to automate lollipop graphs
    n_pcs <- length(pcs)

    if (n_pcs == 2) {
      # 2D plot
      title <- sprintf("PCA Plot of Principal Components %d-%d (%.4f%%)",
                       pcs[1], pcs[2], PCA_var[pcs[2], 3])

      axis_labels <- list(
        x = sprintf("Principal Component %d (%.4f%%)",
                    pcs[1], PCA_var[pcs[1], 2]),
        y = sprintf("Principal Component %d (%.4f%%)",
                    pcs[2], PCA_var[pcs[2], 2])
      )

    } else if (n_pcs == 3) {
      # 3D plot
      title <- sprintf("PCA Plot of Principal Components %d-%d-%d (%.4f%%)",
                       pcs[1], pcs[2], pcs[3], PCA_var[pcs[3], 3])

      axis_labels <- list(
        x = sprintf("Principal Component %d (%.4f%%)",
                    pcs[1], PCA_var[pcs[1], 2]),
        y = sprintf("Principal Component %d (%.4f%%)",
                    pcs[2], PCA_var[pcs[2], 2]),
        z = sprintf("Principal Component %d (%.4f%%)",
                    pcs[3], PCA_var[pcs[3], 2])
      )
    }

    return(list(title = title, axis_labels = axis_labels))
  }

  #___________________________________________________________________________________________________________________
  if (k == 2) {   # For PCA of landmark configuration with 2 dimensions
    PCA_graph = list()
    PCA_list = list()
    lollipop_data = list()

    if (class(Group) == "list") {
      PCA_group <- list()
      lollipops$PCA_group <- vector("list", length(Group))

      for (i in seq_along(Group)) {
        for (pc_name in names(pc_sets)) {

          pc_set <- pc_sets[[pc_name]]

          if (ncol(Data_PCA$x) >= pc_set$min_dim && PCs >= pc_set$min_dim) {
            PCA_group[[pc_name]] <- hullgen(
              Data_PCA$x,
              select_PC = pc_set$pcs,
              Group = Group[[i]],
              color = NULL,
              ID = ID,
              PCA_var = PCA_var,
              sym = TRUE
            )
          }
        }
        lollipops$PCA_group[[i]] <- PCA_group
      }
      names(lollipops$PCA_group) <- names(Group)
    }

    for (pc_name in names(pc_sets)) {
      pc_set <- pc_sets[[pc_name]]
      pcs <- pc_set$pcs
      data <- data.frame(Data_PCA$x)

      # Create labels
      labels <- create_plot_labels(pcs, PCA_var)

      # Create base plot
      if (length(pcs) == 2) {
        # 2D plot
        plot <- plot_ly(data = data,
                        x = as.formula(sprintf("~Comp%d", pcs[1])),
                        y = as.formula(sprintf("~Comp%d", pcs[2])),
                        type = 'scatter',
                        mode = 'markers',
                        text = ID,
                        marker = list(size = 9)) %>%
          layout(title = labels$title,
                 xaxis = list(title = labels$axis_labels$x),
                 yaxis = list(title = labels$axis_labels$y))
      } else if (length(pcs) == 3) {
        # 3D plot
        plot <- plot_ly(data = data,
                        x = as.formula(sprintf("~Comp%d", pcs[1])),
                        y = as.formula(sprintf("~Comp%d", pcs[2])),
                        z = as.formula(sprintf("~Comp%d", pcs[3])),
                        type = 'scatter3d',
                        mode = 'markers',
                        text = ID,
                        marker = list(size = 9)) %>%
          layout(title = labels$title,
                 scene = list(
                   xaxis = list(title = labels$axis_labels$x),
                   yaxis = list(title = labels$axis_labels$y),
                   zaxis = list(title = labels$axis_labels$z)
                 ))
      }

      PCA_list[[pc_name]] <- plot
    }

    lollipops$PCA_list <- PCA_list

    if (isFALSE(no.shape)) {
      # Account for PCs with landmark data that is only two-dimensional
      mean_shape = arrayspecs(t(data.frame(Data_PCA$center)), length(Data_PCA$center)/2, 2)
      PC_shape_list = get_extreme_shapes(Data_PCA, k = 2, PCs)

      lollipops$PC_min_max_mean <- PC_shape_list

      for (i in 1:PCs) { # To wrangle the internal function in an output that plot_ly can graph
        if(is.null(subset)) {
          mean_shape <- data.frame(X = mean_shape[,1], Y = mean_shape[,2])
          pos_shape <- data.frame(X = PC_shape_list[[i+1]][,1], Y = PC_shape_list[[i+1]][,2])
          neg_shape <- data.frame(X = PC_shape_list[[i]][,1], Y = PC_shape_list[[i]][,2])

          lollipops$PC_mean_max_min[[i]] <- list(mean_shape, pos_shape, neg_shape)

          # Initialize the Plotly graph with Mean shape points
          PCA_graph <- plot_ly()
          PCA_graph <- PCA_graph %>%
            add_trace(data = mean_shape,
                      x = ~X, y = ~Y,
                      type = 'scatter', mode = 'markers', text = coord_name,
                      marker = list(size = 2, color = "black"),
                      name = 'Mean Shape')

          x_vals <- c(rbind(pos_shape$X, mean_shape$X))
          y_vals <- c(rbind(pos_shape$Y, mean_shape$Y))

          # Add a single trace for all positive shape lines
          PCA_graph <- PCA_graph %>%
            add_trace(x = x_vals, y = y_vals,
                      type = 'scatter', mode = 'lines', text = coord_name,
                      line = list(color = "blue", width = 2),
                      name = 'Positive Shape')

          x_vals <- c(rbind(neg_shape$X, mean_shape$X))
          y_vals <- c(rbind(neg_shape$Y, mean_shape$Y))

          # Add a single trace for all negative shape lines
          PCA_graph <- PCA_graph %>%
            add_trace(x = x_vals, y = y_vals,
                      type = 'scatter', mode = 'lines', text = coord_name,
                      line = list(color = "orange", width = 2),
                      name = 'Negative Shape')

          # Add a title to the plot
          PCA_graph <- PCA_graph %>%
            layout(title = paste("PCA Lollipop of Shape Changes along Principal Component", i,
                                 "(", round(PCA_var[i,2],4), ")"), scene = list(
                                   xaxis = list(showgrid = FALSE, zeroline = FALSE,
                                                showticklabels = FALSE, title = list(text = "")),
                                   yaxis = list(showgrid = FALSE, zeroline = FALSE,
                                                showticklabels = FALSE, title = list(text = ""))))

          # For each meaningful PC, store the lollipop graph results
          lollipops$lollipop_PCs[[i]] <- PCA_graph

        } else { # if there are subsets

          mean_shape <- data.frame(X = mean[,1,], Y = mean[,2,], subset = subset, coord_name = coord_name)
          pos_shape <- data.frame(X = PC_shape_list[[i+1]][,1,], Y = PC_shape_list[[i+1]][,2,],
                                  subset = subset, coord_name = coord_name)
          neg_shape <- data.frame(X = PC_shape_list[[i]][,1,], Y = PC_shape_list[[i]][,2,],
                                  subset = subset, coord_name = coord_name)

          lollipops$PC_mean_max_min[[i]] <- list(mean_shape, pos_shape, neg_shape)

          add_group_traces <- function(graph, data, group_name, base_color, j, PCA_var) {
            regions <- unique(data$subset)
            for (i in seq_along(regions)) {
              region_data <- filter(data, subset == regions[i])
              graph <- graph %>%
                add_trace(data = region_data,
                          x = ~X, y = ~Y,
                          type = 'scatter3d', mode = 'markers', text = ~coord_name,
                          marker = list(size = 4, color = base_color),
                          name = paste(group_name, regions[i]))
              graph <- graph %>% layout(title = paste("PCA Lollipop of Shape Changes along Principal Component", j,
                                                      "(", round(PCA_var[j,2],4), ")"), scene = list(
                                                        xaxis = list(showgrid = FALSE, zeroline = FALSE,
                                                                     showticklabels = FALSE, title = list(text = "")),
                                                        yaxis = list(showgrid = FALSE, zeroline = FALSE,
                                                                     showticklabels = FALSE, title = list(text = "")),
                                                        zaxis = list(showgrid = FALSE, zeroline = FALSE,
                                                                     showticklabels = FALSE, title = list(text = "")),
                                                        dragmode = "turntable"))
            }
            return(graph)
          }

          PCA_graph = plot_ly()
          # Add traces for each main group and its subgroups
          PCA_graph <- add_group_traces(PCA_graph, mean_shape, 'Mean Shape', "black", j = i, PCA_var)

          PCA_graph <- add_group_traces(PCA_graph, pos_shape, 'Positive Shape', "blue", j = i, PCA_var)

          PCA_graph <- add_group_traces(PCA_graph, neg_shape, 'Negative Shape', "orange", j = i, PCA_var)

          lollipops$lollipop_PCs[[i]] <- PCA_graph
        }
      }
    }
  }

  #___________________________________________________________________________________________________________________
  if (k == 3) { # PCA for landmarks with 3 dimensions or more
    PCA_graph = list()
    PCA_data = list()
    PCA_list = list()
    lollipop_data = list()


    if (class(Group) == "list") {
      PCA_group <- list()
      lollipops$PCA_group <- vector("list", length(Group))

      for (i in seq_along(Group)) {
        for (pc_name in names(pc_sets)) {

          pc_set <- pc_sets[[pc_name]]

          if (ncol(Data_PCA$x) >= pc_set$min_dim && PCs >= pc_set$min_dim) {
            PCA_group[[pc_name]] <- hullgen(
              Data_PCA$x,
              select_PC = pc_set$pcs,
              Group = Group[[i]],
              color = NULL,
              ID = ID,
              PCA_var = PCA_var,
              sym = TRUE
            )
          }
        }
        lollipops$PCA_group[[i]] <- PCA_group
      }
      names(lollipops$PCA_group) <- names(Group)
    }

    for (pc_name in names(pc_sets)) {
      pc_set <- pc_sets[[pc_name]]
      pcs <- pc_set$pcs
      data <- data.frame(Data_PCA$x)

      # Create labels
      labels <- create_plot_labels(pcs, PCA_var)

      # Create base plot
      if (length(pcs) == 2) {
        # 2D plot
        plot <- plot_ly(data = data,
                        x = as.formula(sprintf("~Comp%d", pcs[1])),
                        y = as.formula(sprintf("~Comp%d", pcs[2])),
                        type = 'scatter',
                        mode = 'markers',
                        text = ID,
                        marker = list(size = 9)) %>%
          layout(title = labels$title,
                 xaxis = list(title = labels$axis_labels$x),
                 yaxis = list(title = labels$axis_labels$y))
      } else if (length(pcs) == 3) {
        # 3D plot
        plot <- plot_ly(data = data,
                        x = as.formula(sprintf("~Comp%d", pcs[1])),
                        y = as.formula(sprintf("~Comp%d", pcs[2])),
                        z = as.formula(sprintf("~Comp%d", pcs[3])),
                        type = 'scatter3d',
                        mode = 'markers',
                        text = ID,
                        marker = list(size = 9)) %>%
          layout(title = labels$title,
                 scene = list(
                   xaxis = list(title = labels$axis_labels$x),
                   yaxis = list(title = labels$axis_labels$y),
                   zaxis = list(title = labels$axis_labels$z)
                 ))
      }

      PCA_list[[pc_name]] <- plot
    }

    lollipops$PCA_list <- PCA_list

    if (isFALSE(no.shape)) {

      PC_mean_max_min = list() # Object to store the shape extremes and mean shape of each meaningful PC
      mean = arrayspecs(t(data.frame(Data_PCA$center)), (length(Data_PCA$center)/3), 3)
      PC_shape_list = get_extreme_shapes(Data_PCA, k = 3, PCs)

      for (i in 1:PCs) { # Necessary for wrangling data into a format that plot_ly can graph

        if(is.null(subset)){
          mean_shape <- data.frame(X = mean[,1,], Y = mean[,2,], Z = mean[,3,])
          pos_shape <- data.frame(X = PC_shape_list[[i+1]][,1,], Y = PC_shape_list[[i+1]][,2,],
                                  Z = PC_shape_list[[i+1]][,3,])
          neg_shape <- data.frame(X = PC_shape_list[[i]][,1,], Y = PC_shape_list[[i]][,2,], Z = PC_shape_list[[i]][,3,])

          lollipops$PC_mean_max_min[[i]] <- list(mean_shape, pos_shape, neg_shape)

          # Initialize the Plotly graph with Mean shape points

          PCA_graph <- plot_ly()

          PCA_graph <- PCA_graph %>%
            add_trace(data = mean_shape,
                      x = ~X, y = ~Y, z = ~Z,
                      type = 'scatter3d', mode = 'markers', text = coord_name,
                      marker = list(size = 4, color = "black"),
                      name = 'Mean Shape')

          PCA_graph <- PCA_graph %>%
            add_trace(data = pos_shape,
                      x = ~X, y = ~Y, z = ~Z,
                      type = 'scatter3d', mode = 'markers', text = coord_name,
                      marker = list(size = 4, color = "blue"),
                      name = 'Positive Shape')

          PCA_graph <- PCA_graph %>%
            add_trace(data = neg_shape,
                      x = ~X, y = ~Y, z = ~Z,
                      type = 'scatter3d', mode = 'markers', text = coord_name,
                      marker = list(size = 4, color = "orange"),
                      name = 'Negative Shape')

          x_pos_vals <- c(rbind(mean_shape$X, pos_shape$X))
          y_pos_vals <- c(rbind(mean_shape$Y, pos_shape$Y))
          z_pos_vals <- c(rbind(mean_shape$Z, pos_shape$Z))

          # Add each line trace for positive shape
          PCA_graph <- PCA_graph %>%
            add_trace(x = x_pos_vals, y = y_pos_vals, z = z_pos_vals,
                      type = 'scatter3d', mode = 'lines', name = 'Pos Shape Line',
                      line = list(color = "blue", width = 2))

          x_neg_vals <- c(rbind(mean_shape$X, neg_shape$X))
          y_neg_vals <- c(rbind(mean_shape$Y, neg_shape$Y))
          z_neg_vals <- c(rbind(mean_shape$Z, neg_shape$Z))


          PCA_graph <- PCA_graph %>%
            add_trace(x = x_neg_vals, y = y_neg_vals, z = z_neg_vals,
                      type = 'scatter3d', mode = 'lines', name = 'Neg Shape Line',
                      line = list(color = "orange", width = 2))

          # Layout configuration
          PCA_graph <- PCA_graph %>%
            layout(title = paste("PCA Lollipop of Shape Changes along Principal Component", i,
                                 "(", round(PCA_var[i,2],4), ")"), scene = list(
                                   xaxis = list(showgrid = FALSE, zeroline = FALSE,
                                                showticklabels = FALSE, title = list(text = "")),
                                   yaxis = list(showgrid = FALSE, zeroline = FALSE,
                                                showticklabels = FALSE, title = list(text = "")),
                                   zaxis = list(showgrid = FALSE, zeroline = FALSE,
                                                showticklabels = FALSE, title = list(text = "")),
                                   dragmode = "turntable"))

          lollipops$lollipop_PCs[[i]] <- PCA_graph

        } else { #if there are subsets

          mean_shape <- data.frame(X = mean[,1,], Y = mean[,2,], Z = mean[,3,], subset = subset, coord_name = coord_name)
          pos_shape <- data.frame(X = PC_shape_list[[i+1]][,1,], Y = PC_shape_list[[i+1]][,2,],
                                  Z = PC_shape_list[[i+1]][,3,], subset = subset, coord_name = coord_name)
          neg_shape <- data.frame(X = PC_shape_list[[i]][,1,], Y = PC_shape_list[[i]][,2,], Z = PC_shape_list[[i]][,3,],
                                  subset = subset, coord_name = coord_name)

          lollipops$PC_mean_max_min[[i]] <- list(mean_shape, pos_shape, neg_shape)

          add_group_traces <- function(graph, data, group_name, base_color, j, PCA_var) {
            regions <- unique(data$subset)
            for (i in seq_along(regions)) {
              region_data <- filter(data, subset == regions[i])
              graph <- graph %>%
                add_trace(data = region_data,
                          x = ~X, y = ~Y, z = ~Z,
                          type = 'scatter3d', mode = 'markers', text = ~coord_name,
                          marker = list(size = 4, color = base_color),
                          name = paste(group_name, regions[i]))
              graph <- graph %>% layout(title = paste("PCA Lollipop of Shape Changes along Principal Component", j,
                                                      "(", round(PCA_var[j,2],4), ")"), scene = list(
                                                        xaxis = list(showgrid = FALSE, zeroline = FALSE,
                                                                     showticklabels = FALSE, title = list(text = "")),
                                                        yaxis = list(showgrid = FALSE, zeroline = FALSE,
                                                                     showticklabels = FALSE, title = list(text = "")),
                                                        zaxis = list(showgrid = FALSE, zeroline = FALSE,
                                                                     showticklabels = FALSE, title = list(text = "")),
                                                        dragmode = "turntable"))
            }
            return(graph)
          }

          PCA_graph = plot_ly()
          # Add traces for each main group and its subgroups
          PCA_graph <- add_group_traces(PCA_graph, mean_shape, 'Mean Shape', "black", j = i, PCA_var)

          PCA_graph <- add_group_traces(PCA_graph, pos_shape, 'Positive Shape', "blue", j = i, PCA_var)

          PCA_graph <- add_group_traces(PCA_graph, neg_shape, 'Negative Shape', "orange", j = i, PCA_var)

          lollipops$lollipop_PCs[[i]] <- PCA_graph
        }
      }
    }
  }
  #_________________________________________________________
  return(lollipops)  # return internal function output
} # End of internal lolligen graphing function
